export const START_REQUEST = 'START_REQUEST';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const SET_CONTACTS = 'SET_CONTACTS';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SET_CONTACT_INFO = 'SET_CONTACT_INFO';